### ISSUE TITLE
input_boolean.on_state

### ISSUE THREAD

**Issue by AarvdH** [Anashost/MY-HA-DASH#8]
Hi,
What a magnificent work you did on this dashboard. I now have Home Assistant for two years and is growing and growing.
The right dashboard stayed behind until now. Thanks for your effort.
I don't have an issue but i can't really figure out where for the 'input_boolean.on_state' is.
I did apply it off course, and I can see that in the hole code you have been using it. But it doesn't matter if it is On or Off.
Can you please explain it a little bit further for me?

Thank you.
Hans.

**Comment by Anashost** [comment]
Really glad you like it,
As of the `input_boolean.on_state` it should stay `on` all the time. 

The reason behind this approach is that, in some cards, like the mushroom cards (in the header for example):

![Screenshot_20231124_132422_Home Assistant](https://github.com/Anashost/MY-HA-DASH/assets/41167157/9e770058-ea3f-4a45-a112-5a4349324a42)

The card won't be colored unless it has an entity with `on` state. So I'm using the `input_boolean.on_state` for cards that I want to be colored all the time.

In the `lights card` in the header for example, I'm `not` using that because I want it to be colored only if a light is turned on. So it gets its state from `group.all_lights`

Hope it's clear now :-)

**Comment by AarvdH** [comment]
Yes all clear and works as it should be...
Thank you
